name: remote ssh command
on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY1 }}
        port: ${{ secrets.PORT }}
        script: whoami
        
#    testing01:
#       name: image update
#       runs-on: ubuntu-latest
#       steps:
#        - name: checkout
#          uses: actions/checkout@v1
#        - name: executing remote ssh commands using ssh key
#          uses: easingthemes/ssh-deploy@main
#          with:
#            host: ${{ secrets.HOST }}
#            username: ${{ secrets.USERNAME }}
#            key: ${{ secrets.KEY }}
#            port: ${{ secrets.PORT }}
#            script: |
#              whoami
#              microk8s kubectl set image deployment/my-web-app my-web-app=rubisha/firstgo:latest
#              exit
# # name: Push-to-EC2

# Trigger deployment only on push to master branch
# on:
#    workflow_dispatch:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     name: Deploy to EC2 on master branch push
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the files
#         uses: actions/checkout@v2

#       - name: Deploy to Server 1
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{secrets.KEY}}
#           REMOTE_HOST: ${{secrets.HOST}}
#           REMOTE_USER: ${{ secrets.USERNAME }}
#           TARGET: ${{ secrets.TARGET_DIR }}
