name: deploy
on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY1 }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          sudo -i
          docker pull rubisha:firstgo:main
          microk8s kubectl set image deployment/my-web-app my-web-app=rubisha/firstgo:latest
          exit
        
