# name: remote ssh command
# on: [push]

# jobs:
#    testing01:
#       name: image update
#       runs-on: ubuntu-latest
#       steps:
#        - name: checkout
#          uses: actions/checkout@v1
#        - name: executing remote ssh commands using ssh key
#          uses: ./
#          with:
#            host: ${{ secrets.HOST }}
#            username: ${{ secrets.USERNAME }}
#            key: ${{ secrets.KEY }}
#            port: ${{ secrets.PORT }}
#            script: |
#              whoami
#              microk8s kubectl set image deployment/my-web-app my-web-app=rubisha/firstgo:latest
          
